### ISSUE TITLE
Downloading the training data

### ISSUE THREAD

**Issue by mmabrouk** [dellacortelab/prospr#1]
Dear Wendy, Bryce and Todd,

Thank you first for developing and open sourcing the Alphafold method. I have tried downloading the training data from Box.com, but the website does not allow downloads of more than 15 GB, which means one has to manually download the ~28000 files ten by ten. Do you know a solution to this problem? 

Thank you!
Yours,
Mahmoud

**Comment by tyggna** [comment]
We're discussing the best way to solve that right now, but it's going to require 
I'm planning on making it an option to download the data through prospr itself in the future.

**Comment by wbillings** [comment]
All of the training data, databases, and saved network weights can now be accessed at https://files.physics.byu.edu/data/prospr/ This should allow for programmatic access (wget, etc.)

**Comment by mmabrouk** [comment]
Thanks! That is awesome!
