### ISSUE TITLE
a reference model

### ISSUE THREAD

**Issue by ybwu01** [dellacortelab/prospr#18]
Hi, Thank you so much for open-sourcing the code. The main text also mentioned a reference model, however, the link to the model is missing (https://files.physics.byu.edu/data/prospr/models/). Did you use the reference model to produce the images you just posted to compare them to those produced by alphafold? The results are amazing. I was wondering if the reference model helps. 
Also, could you provide the re-bin script from 64 bins to 10 bins if possible? Your help is much appreciated.

**Comment by wbillings** [comment]
The reference model is included in the link you sent, labeled ProSPr_ref (short for reference). We did not end up using it for any of the analysis done in the manuscript nor the prediction comparison shown in the readme.
For those rebinned heat maps, we actually just took the argmax of the distogram at each i,j pair, converted it to the distance in Å, determined which CASP14 bin range contained that distance, and displayed that bin value in the image (0-9). To rebin the actual probabilities you could use the CASP14 10-bin mapping (website referenced in readme) and the mapping of the ProSPr bins (see this thread: #16) However, the ProSPr bins do not line up evenly with angstrom cutoffs defined for CASP, so it would be up to some interpretation as to which distance range the ProSPr bins straddling the cutoff lines should contribute their probability.

**Comment by ybwu01** [comment]
Thank you.
