### ISSUE TITLE
Unable to use prospr with multiple issues

### ISSUE THREAD

**Issue by dangerzone** [dellacortelab/prospr#21]
Hello,

Thank you for releasing this! I'm excited to use it, but have have been running into a lot of issues in trying to. 

I attempted using it both with and without a docker container, including building a docker image based on the updated code on the master branch of this repo.
I also attempted downloading the plmDCA package from FTP site mentioned on the README.

All of my attempts ended in failure.

Using the off-the-shelf docker container also doesn't work:
```
docker run -it -v /home/dangerzone/data/:/data prospr/prospr build example_protein
```
Which resulted in the following error.
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/hhmake -i /data/example_protein/example_protein.a3m -o /data/example_protein/example_protein.hhm': '/usr/local/bin/hhmake -i /data/example_protein/example_protein.a3m -o /data/example_protein/example_protein.hhm'
```

This error is simple enough to fix (and I think it is fixed in the version of hhblits.py in the master branch), but I ran into basically every one of the other open issue tickets in this Github repo. Most of them having to do with the plmDCA dependency.

I have two concrete questions:
Are there any plans to release an updated docker image?
Is it possible to not use plmDCA and it's dependencies? https://github.com/KIT-MBS/pydca might be a good starting point.

**Comment by yamule** [comment]
I'm running prospr with julia version of plmDCA https://github.com/pagnani/PlmDCA/ .
Implementing it took about 3 days.
(But it's an old version which is using julia v0.7. )

According to the https://github.com/dellacortelab/prospr/issues/20 , the authors are planning to remove the dependencies.

**Comment by yamule** [comment]
https://github.com/yamule/prospr/tree/sep
I share the Prospr files I'm using. It accepts input files separately, therefore you may run it with pydca.

**Comment by dangerzone** [comment]
Thank you @yamule !!!

**Comment by yamule** [comment]
You are welcome.
I found that it's heavily customized for my personal preferences. Please arrange run.py if you want the original outputs.

**Comment by wbillings** [comment]
We are sorry about all of the dependency issues. We plan to release a complete update within the coming months that will hopefully improve usability by removing MATLAB and other problematic requirements. It will also include a heavily restructured ProSPr network, updated model files, and improved results.
