### ISSUE TITLE
Use of multiple threads for generating profiles

### ISSUE THREAD

**Issue by huhlim** [dellacortelab/prospr#4]
I tried to generate profiles with the build option. I found that it was really slow because HHblits was run with 2 threads (its default option) and PSI-BLAST was run with only 1 thread. Modern CPUs for servers have a huge number of threads (ie., Mine has 48 threads). So, I recommend you to get some optional arguments for the number of threads for the input feature generation step, and this would accelerate the step. Indeed, I modified related Python scripts by myself, and it improved in terms of speed.

**Comment by tyggna** [comment]
sounds good, if you want to do a PR, then I'll review it and merge it in.  If not, I won't be able to get to it for a few days
